version: '2'

services:

  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
#      - "9300:9300"
    volumes:
      - elastic-volume:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      discovery.type: single-node
    mem_limit: 2000m
    networks:
      - infra
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 65536

  logstash:
    build: ./logstash/
    ports:
      - "5000:5000"
    environment:
      _JAVA_OPTIONS: -Xmx768m -Xms50m
    mem_limit: 1000m
    depends_on:
      - elasticsearch
    networks:
      - infra

  kibana:
    build: ./kibana/
    ports:
      - "5601:5601"
    environment:
      _JAVA_OPTIONS: -Xmx768m -Xms50m
    mem_limit: 1000m
    depends_on:
      - elasticsearch
    networks:
      - infra

networks:
  infra:
    external:
      name: nimbleinfra_default

volumes:
  elastic-volume: