version: '3'

services:
  solr:
    image: solr:7.6.0
    command: "-cloud"
#    ports:
#      - "8983:8983"
    volumes:
      - solr-volume:/opt/solr/server/solr/
    networks:
      - nimble-cloud-infra

volumes:
  solr-volume:
     external: true

networks:
  nimble-cloud-infra:
    external:
      name: nimbleinfrastaging_default
