version: '2'

services:
  nginx:
    image: nginx:1.15.6
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/certs:/etc/certs:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - efactory-network

networks:
  efactory-network:
    external:
      name: security-network
