version: '2'

services:
  epcis-client:
    image: nimbleplatform/epcis-client:staging
    env_file:
      - ../../services/env_vars
      - ../../services/env_vars-staging
      - ../../services/platform-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms50m
    ports:
      - 8021:8080
    mem_limit: 1000m
    networks:
      - nimble-cloud-infra

networks:
  nimble-cloud-infra:
    external:
      name: nimbleinfrastaging_default
