version: '2'

services:

  ############################
  ##### Identity Service #####
  ############################
 
  identity-service:
    image: nimbleplatform/identity-service:staging
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms64m
    mem_limit: 1000m
    ports:
      - "9096:9096"
    networks:
      - infra

  ############################
  #### Identity Service V2 ###
  ############################

  identity-service-v2:
    image: nimbleplatform/identity-service:staging-v2
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      - APPLICATION_NAME_SUFFIX=-v2
      - POSTGRES_HOST=sl-eu-lon-2-portal.1.dblayer.com
      - POSTGRES_PORT=21736
      - POSTGRES_DB=identitydbv2
      - POSTGRES_USER=admin
      - _JAVA_OPTIONS=-Xmx64m -Xms50m
    mem_limit: 1000m
    networks:
      - infra

  ##############################
  ## Business Process Service ##
  ##############################

  business-process-service:
    image: nimbleplatform/business-process-service:staging
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms50m
    mem_limit: 3000m
    ports:
      - "8085:8085"
    networks:
      - infra

  ##############################
  ####### Indexing Service #####
  ##############################

  indexing-service:
    image: nimbleplatform/indexing-service:staging
    ports:
      - "9101:8080"
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms50m
      - SOLR_HOST=http://solr:8983/solr/
    mem_limit: 1000m
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    networks:
      - infra

  ##############################
  ####### Catalog Service ######  
  ##############################
  
  catalog-service-srdc:
    image: nimbleplatform/catalogue-service-micro:staging
    ports:
      - "10095:8095"
    environment:
      - _JAVA_OPTIONS=-Xmx768m -Xms50m
    mem_limit: 3000m
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    networks:
      - infra

  ##############################
  ####### Search Service ######
  ##############################

  search-service:
    image: nimbleplatform/catalog-search-service:staging
    ports:
      - "10096:8090"
    env_file:
      - env_vars
      - platform-config
    environment:
      - "SPRING_PROFILES_ACTIVE=productive"
      - "MARMOTTA_URL=http://nimble-staging.salzburgresearch.at/marmotta"
      - "LANGUAGE_LABEL=http://www.w3.org/2004/02/skos/core#prefLabel"
      - "CATALOG_SEARCH_CONFIG:/resources/sqpConfiguration-staging.xml"
      - "_JAVA_OPTIONS=-Xmx512m -Xms50m"
    mem_limit: 1000m
    networks:
      - infra

  ###############################
  ###### Frontend Service #######
  ###############################
  
  frontend-service:
    image: nimbleplatform/frontend-service:staging
    ports:
      - "8081:8080"
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx512m -Xms50m
    mem_limit: 400m
    networks:
      - infra
    depends_on:
      - frontend-service-sidecar
  
  frontend-service-sidecar:
    image: nimbleplatform/sidecar:latest
    ports:
      - "9097:9097"
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      SIDECAR_NAME: frontend-service
      SIDECAR_APP_HOST: frontend-service
      SIDECAR_APP_PORT: 8080 # use internal port of network (not publicly exposed)
      SIDECAR_APP_HEALTH_URI: http://frontend-service:8080/health.json
      SIDECAR_APP_HOMEPAGE_URI: http://frontend-service:8080/
      _JAVA_OPTIONS: -Xmx768m -Xms50m
    mem_limit: 600m
    networks:
      - infra

  ###############################
  ##### Frontend Service FMP ####
  ###############################

  frontend-service-fmp:
    image: nimbleplatform/frontend-service:fmp-staging
    ports:
      - "7081:8080"
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx512m -Xms50m
    mem_limit: 400m
    networks:
      - infra
    depends_on:
      - frontend-service-sidecar-fmp

  frontend-service-sidecar-fmp:
    image: nimbleplatform/sidecar:latest
    ports:
      - "7082:9097"
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      SIDECAR_NAME: frontend-service-fmp
      SIDECAR_APP_HOST: frontend-service-fmp
      SIDECAR_APP_PORT: 8080 # use internal port of network (not publicly exposed)
      SIDECAR_APP_HEALTH_URI: http://frontend-service-fmp:8080/health.json
      SIDECAR_APP_HOMEPAGE_URI: http://frontend-service-fmp:8080/
      _JAVA_OPTIONS: -Xmx768m -Xms50m
    mem_limit: 600m
    networks:
      - infra


  ###############################
  ##### Frontend Service EFACTORY ####
  ###############################

  frontend-service-efactory:
    image: nimbleplatform/frontend-service:efac-staging
    ports:
      - "7083:8080"
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx512m -Xms50m
    mem_limit: 400m
    networks:
      - infra
    depends_on:
      - frontend-service-sidecar-efactory

  frontend-service-sidecar-efactory:
    image: nimbleplatform/sidecar:latest
    ports:
      - "7084:9097"
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      SIDECAR_NAME: frontend-service-efactory
      SIDECAR_APP_HOST: frontend-service-efactory
      SIDECAR_APP_PORT: 8080 # use internal port of network (not publicly exposed)
      SIDECAR_APP_HEALTH_URI: http://frontend-service-efactory:8080/health.json
      SIDECAR_APP_HOMEPAGE_URI: http://frontend-service-efactory:8080/
      _JAVA_OPTIONS: -Xmx768m -Xms50m
    mem_limit: 600m
    networks:
      - infra

  ###############################
  ##### Frontend Service EFACTORY ####
  ###############################

  frontend-service-efs:
    image: nimbleplatform/frontend-service:efac-fed-search
    ports:
      - "7083:8080"
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx512m -Xms50m
    mem_limit: 400m
    networks:
      - infra
    depends_on:
      - frontend-service-sidecar-efs

  frontend-service-sidecar-efs:
    image: nimbleplatform/sidecar:latest
    ports:
      - "7084:9097"
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      SIDECAR_NAME: frontend-service-efactory
      SIDECAR_APP_HOST: frontend-service-efactory
      SIDECAR_APP_PORT: 8080 # use internal port of network (not publicly exposed)
      SIDECAR_APP_HEALTH_URI: http://frontend-service-efs:8080/health.json
      SIDECAR_APP_HOMEPAGE_URI: http://frontend-service-efs:8080/
      _JAVA_OPTIONS: -Xmx768m -Xms50m
    mem_limit: 600m
    networks:
      - infra

  ##############################
  ####### Indexing Service efs #####
  ##############################

  indexing-service-efs:
      image: nimbleplatform/indexing-service:staging
      ports:
        - "9101:8080"
      environment:
        - _JAVA_OPTIONS=-Xmx512m -Xms50m
        - SOLR_HOST=https://efactory-security-portal.salzburgresearch.at/solr/
      mem_limit: 1000m
      env_file:
        - env_vars
        - env_vars-staging
        - platform-config
      networks:
        - infra

  ###############################
  #### Data Channel Service #####
  ###############################

  data-channel-service:
    image: nimbleplatform/data-channel-service:staging
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms50m
    mem_limit: 500m
    ports:
      - "9099:9099"
    networks:
      - infra

  ###############################
  #### Data Pipes #####
  ###############################

  data-pipes:
    image: nimbleplatform/data-pipes:staging
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms50m
    mem_limit: 500m
    ports:
      - "8082:8080"
    networks:
      - infra

  ###############################
  ## Tracking Analysis Service ##
  ###############################

  tracking-analysis-service:
    image: nimbleplatform/tracking-analysis-service:staging
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx128m -Xms50m
    mem_limit: 400m
    ports:
      - "9100:9100"
    networks:
      - infra

  ###############################
  ## Tracking Service ##
  ###############################

  tracking-service:
    image: nimbleplatform/tracking-service:staging
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx128m -Xms50m
    mem_limit: 400m
    ports:
      - "8090:8090"
    networks:
      - infra


  ###############################
  ## Data Aggregation Service ###
  ###############################

  data-aggregation-service:
    image: nimbleplatform/data-aggregation-service:staging
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms50m
    mem_limit: 700m
    networks:
      - infra

  ###############################
  ######## Trust Service ########
  ###############################

  trust-service:
    image: nimbleplatform/trust-service:staging
    restart: always
    env_file:
      - env_vars
      - env_vars-staging
      - platform-config
    environment:
      PORT: 9098
      _JAVA_OPTIONS: -Xmx256m -Xms128m
    mem_limit: 800m
    ports:
      - "9098:9098"
    networks:
      - infra

  ###############################
  ######## Delegate Service ########
  ###############################
  delegate-service:
    image: nimbleplatform/delegate-service:staging
    restart: always
    env_file:
      - env_vars
      - env_vars_delegate
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx256m -Xms128m
    mem_limit: 400m
    ports:
      - "9265:8080"
    networks:
      - infra

  ###############################
  ######## Agent Service ########
  ###############################
  agent-service:
    image: nimbleplatform/agent-service:staging
    restart: always
    env_file:
      - env_vars
      - env_vars_delegate
      - platform-config
    mem_limit: 400m
    ports:
      - "8383:8383"
    networks:
      - infra

  ###############################
  ######## EPCIS Service ########
  ###############################
  epcis-service:
    image: nimbleplatform/epcis-server:staging
    env_file:
      - env_vars
      - env_vars_delegate
      - platform-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms50m
      - EPCIS_DB_NAME=epcis
      - EPCIS_DB_SSL=false
      - EPCIS_DB_URL=mongodb://admin:nimble_platform_password@epcis-server-db:27017/
      - IDENTITY_SERVER_URI=http://identity-service:9096
      - EPCIS_SERVICE_URL=http://nimble-dev.ikap.biba.uni-bremen.de/epcis-server
    ports:
      - 8119:8080
    mem_limit: 1000m
    networks:
      - infra


networks:
  infra:
    external:
      name: nimbleinfrastaging_default
