version: '3'

services:
  ##########################
  #### MS Infrastructure ###
  ##########################

  config-server:
    image: nimbleplatform/config-server:latest
    env_file:
      - env_vars
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms50m
    ports:
      - "8888:8888"
    networks:
      - infra

  service-discovery:
    image: nimbleplatform/service-discovery:latest
    env_file:
      - env_vars
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms50m
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - infra

  gateway-proxy:
    image: nimbleplatform/gateway-proxy:latest
    env_file:
      - env_vars
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms50m
#    ports:
#      - "80:80"
    depends_on:
      - config-server
      - service-discovery
    networks:
      - infra

  ##########################
  ######## Databases #######
  ##########################

  staging-main-db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 'IRDMKUYCDTIDNLQG'
    command:
      - "-c"
      - "shared_buffers=300MB"
      - "-c"
      - "max_connections=375"
    ports:
      - 5433:5432
    volumes:
      - staging-main-db:/var/lib/postgresql/data

volumes:
  staging-main-db:
     external: true
networks:
  infra:
    external:
      name: nimbleinfrastaging_default
