version: '3'

services:

  ##############################
  ######## Apache Kafka ########
  # ( for internal messaging ) #
  ##############################

  kafka:
    image: nimbleplatform/kafka_infra:latest # derived from https://github.com/wurstmeister/kafka-docker
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "business-process-updates-staging:1:1,trust-score-updates-staging:1:1,company-updates-staging:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      _JAVA_OPTIONS: -Xmx256m -Xms50m
    depends_on:
      - zookeeper
    networks:
      - infra

  zookeeper:
    image: nimbleplatform/zookeeper:3.4
    networks:
      - infra


networks:
  infra:
    external:
      name: nimbleinfrastaging_default
