version: '3'

services:
  ##############################
  ####### Indexing Service #####
  ##############################

  indexing-service:
    image: nimbleplatform/indexing-service:staging
    ports:
      - "9101:8080"
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms50m
      - SOLR_HOST=http://solr:8983/solr/
      #    mem_limit: 1000m
    env_file:
      - env_vars
    networks:
      - efactory-network

  ###############################
  ###### Frontend Service #######
  ###############################

  frontend-service:
    image: nimbleplatform/frontend-service:staging
    ports:
      - "8081:8080"
    env_file:
      - env_vars
      - platform-config
    environment:
      _JAVA_OPTIONS: -Xmx512m -Xms50m
    mem_limit: 1000m
    networks:
      - efactory-network
    depends_on:
      - frontend-service-sidecar

  frontend-service-sidecar:
    image: nimbleplatform/sidecar:latest
    ports:
      - "9097:9097"
    env_file:
      - env_vars
      - platform-config
    environment:
      SIDECAR_NAME: frontend-service
      SIDECAR_APP_HOST: frontend-service
      SIDECAR_APP_PORT: 8080 # use internal port of network (not publicly exposed)
      SIDECAR_APP_HEALTH_URI: http://frontend-service:8080/health.json
      SIDECAR_APP_HOMEPAGE_URI: http://frontend-service:8080/
      _JAVA_OPTIONS: -Xmx768m -Xms50m
    mem_limit: 1000m
    networks:
      - efactory-network

  asg-importer:
    image: nimbleplatform/asg-importer:latest
    environment:
      EFS_URL:
      SR_URL:
      X_API_KEY:
      CLIENT_ID:
      CLIENT_SECRET:
    networks:
      - efactory-network

networks:
  efactory-network:
    external:
      name: security-network
