version: '2'

services:
  apisix:
    image: nimbleplatform/apisix-master:latest
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - 9080:9080
      - 9443:9443
#    networks:
#      - efactory-network

  etcd:
    image: gcr.io/etcd-development/etcd:v3.3.12
    command: /usr/local/bin/etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379
    restart: always
    volumes:
      - ./etcd_data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
    ports:
      - "127.0.0.1:2379:2379/tcp"
#    networks:
#      - efactory-network

volumes:
  etcd_data:

#networks:
#  efactory-network:
#    external:
#      name: security-network
